# Generated by Django 5.2.8 on 2026-01-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.TextField(verbose_name='User Request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('executing', 'Executing'), ('verifying', 'Verifying'), ('reporting', 'Reporting'), ('completed', 'Completed'), ('failed', 'Failed'), ('dialog_only', 'Dialog Only')], default='pending', max_length=20, verbose_name='Status')),
                ('current_agent', models.CharField(blank=True, max_length=50, verbose_name='Current Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('result_summary', models.TextField(blank=True, verbose_name='Result Summary')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('html_content', models.TextField(verbose_name='HTML Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ai_admin.tasklog', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Report',
                'verbose_name_plural': 'Task Reports',
            },
        ),
    ]
