from django.db import models
from django.utils.translation import gettext_lazy as _

class TaskLog(models.Model):
    """
    Logs the lifecycle of an administrative task.
    """
    STATUS_CHOICES = [
        ('pending', _('Pending')),
        ('analyzing', _('Analyzing')),
        ('executing', _('Executing')),
        ('verifying', _('Verifying')),
        ('reporting', _('Reporting')),
        ('completed', _('Completed')),
        ('failed', _('Failed')),
        ('dialog_only', _('Dialog Only')),
    ]

    user_request = models.TextField(_("User Request"))
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default='pending')
    current_agent = models.CharField(_("Current Agent"), max_length=50, blank=True)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated At"), auto_now=True)
    result_summary = models.TextField(_("Result Summary"), blank=True)
    error_message = models.TextField(_("Error Message"), blank=True)

    class Meta:
        verbose_name = _("Task Log")
        verbose_name_plural = _("Task Logs")
        ordering = ['-created_at']

    def __str__(self):
        return f"Task {self.id}: {self.status}"


class TaskReport(models.Model):
    """
    Stores the detailed HTML report generated by the Description Agent.
    """
    task = models.OneToOneField(TaskLog, on_delete=models.CASCADE, related_name='report', verbose_name=_("Task"))
    slug = models.SlugField(_("Slug"), unique=True, max_length=255)
    html_content = models.TextField(_("HTML Content"))
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)

    class Meta:
        verbose_name = _("Task Report")
        verbose_name_plural = _("Task Reports")

    def __str__(self):
        return f"Report for Task {self.task.id}"
