# Generated by Django 5.2.8 on 2025-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Например: 47.578300', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Например: 41.099300', max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_zoom',
            field=models.IntegerField(default=16, help_text='Значение от 1 до 19 (16-17 для улицы)', verbose_name='Масштаб карты'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='clinic_name',
            field=models.CharField(max_length=100, verbose_name='Название клиники'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(max_length=200, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='yandex_map_embed_code',
            field=models.TextField(blank=True, help_text='Альтернативный способ: вставьте HTML-код карты из Яндекс.Конструктора', verbose_name='Embed-код карты'),
        ),
    ]
