# Generated by Django 5.2.8 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contactinfo_options_contactinfo_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactsPageText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(
                        default="Как нас найти",
                        max_length=200,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "header_subtitle",
                    models.TextField(
                        default="Мы всегда на связи и готовы помочь вашим питомцам",
                        verbose_name="Подзаголовок страницы",
                    ),
                ),
                (
                    "form_title",
                    models.CharField(
                        default="Напишите нам",
                        max_length=200,
                        verbose_name="Заголовок формы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тексты страницы 'Контакты'",
                "verbose_name_plural": "Тексты страницы 'Контакты'",
            },
        ),
    ]
