# Generated by Django 5.2.8 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True, verbose_name="Ключ (slug)")),
                ("text", models.CharField(max_length=255, verbose_name="Текст")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Описание (где используется)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общая фраза",
                "verbose_name_plural": "Общие фразы",
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_location",
                    models.CharField(
                        default="Ветеринарная клиника в Константиновске",
                        max_length=100,
                        verbose_name="Бейдж: Локация",
                    ),
                ),
                (
                    "badge_work_hours",
                    models.CharField(
                        default="Работаем 24/7",
                        max_length=100,
                        verbose_name="Бейдж: Часы работы",
                    ),
                ),
                (
                    "badge_license",
                    models.CharField(
                        default="Лицензия",
                        max_length=100,
                        verbose_name="Бейдж: Лицензия",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Забота о здоровье ваших питомцев — наша миссия",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "lead_text",
                    models.TextField(
                        default="Современная ветеринарная клиника с опытными специалистами и передовым оборудованием. Мы лечим с любовью!",
                        verbose_name="Лид-текст",
                    ),
                ),
                (
                    "button_primary_text",
                    models.CharField(
                        default="Записаться на приём",
                        max_length=100,
                        verbose_name="Текст основной кнопки",
                    ),
                ),
                (
                    "button_secondary_text",
                    models.CharField(
                        default="Наши услуги",
                        max_length=100,
                        verbose_name="Текст вторичной кнопки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Герой-секция (Главная)",
                "verbose_name_plural": "Герой-секция (Главная)",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="ВетКлиника",
                        max_length=100,
                        verbose_name="Заголовок сайта",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Текст в подвале"),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2025 ВетКлиника. Все права защищены.",
                        max_length=200,
                        verbose_name="Текст копирайта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="StatItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, verbose_name="Число (например: 15+)"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Подпись")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
                "ordering": ["order"],
            },
        ),
    ]
