# Generated by Django 5.2.8 on 2025-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('pet_name', models.CharField(blank=True, max_length=100, verbose_name='Имя питомца')),
                ('pet_type', models.CharField(blank=True, max_length=50, verbose_name='Вид питомца')),
                ('rating', models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★☆'), (3, '★★★☆☆'), (2, '★★☆☆☆'), (1, '★☆☆☆☆')], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
