# Generated by Django 5.2.8 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewsPageText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(
                        default="Отзывы наших клиентов",
                        max_length=200,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "header_subtitle",
                    models.TextField(
                        default="Мы ценим доверие каждого владельца и любовь каждого питомца",
                        verbose_name="Подзаголовок страницы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тексты страницы 'Отзывы'",
                "verbose_name_plural": "Тексты страницы 'Отзывы'",
            },
        ),
    ]
