# Generated by Django 5.2.8 on 2026-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(
                        default="Почему выбирают нас?",
                        max_length=200,
                        verbose_name="Заголовок секции преимуществ",
                    ),
                ),
                (
                    "header_subtitle",
                    models.TextField(
                        default="Мы создали клинику, в которую хотели бы обратиться сами. Здесь каждый питомец получает внимание и заботу.",
                        verbose_name="Подзаголовок секции преимуществ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тексты страницы 'О клинике'",
                "verbose_name_plural": "Тексты страницы 'О клинике'",
            },
        ),
        migrations.CreateModel(
            name="FeatureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="CSS класс иконки Bootstrap (например: bi-people)",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="aboutcontent",
            options={
                "verbose_name": "Контент страницы 'О нас'",
                "verbose_name_plural": "Контент страницы 'О нас'",
            },
        ),
        migrations.AlterModelOptions(
            name="veterinarian",
            options={
                "ordering": ["order"],
                "verbose_name": "Ветеринар",
                "verbose_name_plural": "Ветеринары",
            },
        ),
        migrations.AlterField(
            model_name="aboutcontent",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="aboutcontent",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="about/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="aboutcontent",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="aboutcontent",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="bio",
            field=models.TextField(verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Порядок отображения", verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="vets/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Должность"),
        ),
    ]
